### ISSUE TITLE
File manager context with Windows explorer sometimes not active

### ISSUE THREAD

**Issue by timo95** [knausj85/knausj_talon#437] opened 2021-05-27 15:44 UTC
Task-Manager:
![grafik](https://user-images.githubusercontent.com/24251362/119855133-f45cbe00-bf11-11eb-8f6e-f3740162dffa.png)

The first was opened via `Open ~/talon` and the second via `This PC`.
`explorer.exe` activates the file manager context, `Explorer.EXE` does not.

**Comment by knausj85** [comment] 2021-07-03 06:21
I can't reproduce this one.

There are commands that are known not to work with the "This PC" since it's not a real path. This include the follow/open/etc paths

**Comment by timo95** [comment] 2021-07-03 07:09
![grafik](https://user-images.githubusercontent.com/24251362/124346229-00593100-dbde-11eb-88ec-6a2cc1423685.png)

In both cases the process name is `explorer.exe`, only the command line is different. I looked on the explorer help page to determine if it was active. The context is shown as inactive if i open the explorer via `This PC`. It doesn't matter which path is open. Adding the second variant to `apps.windows_explorer` in `explorer.py` fixed it for me:
```
apps.windows_explorer = """
os: windows
and app.name: Windows Explorer
os: windows
and app.exe: explorer.exe
os: windows
and app.exe: Explorer.EXE
"""
```

**Comment by knausj85** [comment] 2021-07-03 15:17
Ah, thanks for clarifying.

I think the issues with app.name requiring both the exe and friendly name on Windows may be fixed in the forthcoming Talon v0.2, so I wasn't seeing this. It should be released soon - if 0.2 doesn't resolve it for you, I'll merge this in.

**Comment by timo95** [comment] 2021-07-19 08:55
I tried 0.2 and it doesn't work. It doesn't recognize `Windows-Explorer` and `Windows Explorer` as equal. When I change it to this, then it works with 0.2:

```
apps.windows_explorer = """
os: windows
and app.name: Windows-Explorer
os: windows
and app.exe: explorer.exe
"""
```

**Comment by knausj85** [comment] 2021-07-19 16:39
I have added the new application name, thanks for testing it. It might be worth writing up a bug against talon for `Explorer.EXE` versus `explorer.exe`. I suppose it would make sense for it to be always lowercase?

**Closed** 2021-07-19 16:39 UTC
